$(document).ready(()=>{
    $(window).scroll(()=>{
        if(this.scrollY>20){
            $('.navbar').addClass("upDown");
        }
        else
        {
            $('.navbar').removeClass("upDown");
        }
    })
})